name: List macOS software updates

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: List software updates
        run: softwareupdate -list
