name: Latest macOS version

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: List available updates
        run: curl -s https://support.apple.com/en-gb/HT201222 | grep -o 'The latest version of macOS is [0-9]\+\.[0-9]\+\(\.[0-9]\+\)\?' | grep -o '[0-9]\+\.[0-9]\+\(\.[0-9]\+\)\?'
