name: Latest macOS version

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Check for available updates
        run: softwareupdate -l
        id: updates
      - name: Extract macOS version
        run: echo "::set-output name=version::$(echo '${{ steps.updates.outputs.stdout }}' | grep -oE 'macOS [^,]+' | awk '{print $2}')"
        id: macos-version
      - name: Print version
        run: echo "Latest macOS version is ${{ steps.macos-version.outputs.version }}"