name: Latest macOS version

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: List available updates
        run: softwareupdate -l
        id: update-list
      - name: Extract latest version
        run: echo ::set-output name=version::$(echo "${{ steps.update-list.outputs.stdout }}" | grep "macOS" | awk '{print $5}' | cut -d ',' -f 1)
        id: macos-version
      - name: Print version
        run: echo "Latest macOS version is ${{ steps.macos-version.outputs.version }}"
